feat: upgrade rc files

diff --git a/rc/bashrc b/rc/bashrc
--- a/rc/bashrc
+++ b/rc/bashrc
@@ -1,46 +1,22 @@
-# If not running interactively, don't do anything.
-case $- in
-	*i*) ;;
-	*) return;;
-esac
-
-# Make less more friendly for non-text input files, see lesspipe(1).
-[ -x /usr/bin/lesspipe ] && eval "`SHELL=/bin/sh lesspipe`"
-
-# Set variable identifying the chroot you work in (used in the prompt below).
-if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
-	debian_chroot=`cat /etc/debian_chroot`
-fi
-
-# Enable color support of ls.
-if [ -x /usr/bin/dircolors ]; then
-	test -r ~/.dircolors && eval "`dircolors -b ~/.dircolors`" || eval "`dircolors -b`"
-fi
-
-# Enable programmable completion features (you don't need to enable
-# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
-# sources /etc/bash.bashrc).
-if ! shopt -oq posix; then
-	if [ -f /usr/share/bash-completion/bash_completion ]; then
-		. /usr/share/bash-completion/bash_completion
-	elif [ -f /etc/bash_completion ]; then
-		. /etc/bash_completion
-	fi
-fi
-
-# >>> My Default Configs <<<
-
-shopt -s extglob
+# Environment Variables
+HISTCONTROL=ignoreboth:erasedups
+HISTSIZE=-1
+HISTFILESIZE=10000
+PROMPT_COMMAND='history -a'
 
 #PS0="\[\033[00;31m\]\$(printf '%*s' \$(tput cols) '\t ✘')\[\033[00m\]\r"
-PS1='\[\033[00;31m\]\H \$ \[\033[00m\]'
+#PS1='\[\033[00;31m\]\H \$\[\033[00m\] '
 
-unalias -a
-. "$PK_LOAD_CFGBKP/rc/shellrc"
+export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
 
-#cat ~/.cache/current-palette 2>&-
-#feh --bg-center ~/Pictures/wallpapers/wallpaper.png 2>&-
+# Shell Options
+set +o histexpand
+shopt -s extglob globstar
 
-trap erase-history SIGQUIT SIGTERM SIGKILL EXIT
+# Eval Sources
+[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
+[ -r "$HOME/.bash_functions" ] && source "$HOME/.bash_functions"
+[ -r "$HOME/.bash_local" ] && source "$HOME/.bash_local"
 
-# >>>>>>>>>>>>><<<<<<<<<<<<<
+# Shell Cleanup
+#trap erase-history SIGQUIT SIGTERM SIGKILL EXIT
