update: mask output error on token function

diff --git a/rc/shellrc b/rc/shellrc
--- a/rc/shellrc
+++ b/rc/shellrc
@@ -78,20 +78,20 @@ alias llt='ls --color=always -lhtcF'
 ts() { [ "-b" != "$1" ] && LANG=en:pt-br || { LANG=pt-br:en; shift 1; }; trans -b "$LANG" "`eval 'rs "$*"'`"; }
 mkcd() { PATHWAY="${1:?need a pathway to make and go}"; mkdir -pv "$PATHWAY" && cd "$PATHWAY"; pwd; }
 insp() { eval "echo \${${1}}"; }
-psgp() { PATTERN=${1:-need pattern to search!}; ps -xo pid,state,command | grep --color=always -iE "$PATTERN" | head -n -1; }
+psgp() { PATTERN=${1:-need pattern to search}; ps -xo pid,state,command | grep --color=always -iE "$PATTERN" | head -n -1; }
 
 diffstr() { if diff --color=always <(rs "$1") <(rs "$2"); then echo -e "\e[1;32;40mNo differences ✔\e[m"; fi; }
 utilities() { cd /tmp/; highlight -O ansi "$PK_LOAD_LINUX/notes.md" | less -R; cd -; }
-calc() { /usr/bin/bc <<< "scale=${2:-2}; ${1:?nedd a expression to calculate!}"; }
+calc() { /usr/bin/bc <<< "scale=${2:-2}; ${1:?nedd a expression to calculate}"; }
 repeater() { for _ in `seq "$1"`; do eval "${@:2}"; done; }
-calcr() { /usr/bin/bc <<< "scale=1; x=${1:?nedd a expression to calculate!}; if (x < 0) x-=.5 else x+=.5; scale=0; x/1"; }
+calcr() { /usr/bin/bc <<< "scale=1; x=${1:?nedd a expression to calculate}; if (x < 0) x-=.5 else x+=.5; scale=0; x/1"; }
 
 ll() { ROUTE=$([ "$#" -eq 0 ] && pwd || echo "$1"); ls -lhF --time-style=+%% --color=always "$ROUTE"; echo "count `ls -1 "$ROUTE" | wc -l`"; }
 lla() { ROUTE=$([ "$#" -eq 0 ] && pwd || echo "$1"); ls -lhAF --time-style=+%% --color=always "$ROUTE"; echo "count `ls -A1 "$ROUTE" | wc -l`"; }
 
 # >>> Depreceated!
 #readmd() { pandoc -f markdown "${1}" | lynx -stdin; }
-#ae() { [ -f "${1}" ] && echo 'file exists!' || echo 'file not exists!'; }
+#ae() { [ -f "${1}" ] && echo 'file exists' || echo 'file not exists'; }
 #get-alias() { alias "$1" | sed -nE "s/^.*'(.*)'$/\1/p"; }
 
 # Long.
@@ -105,19 +105,6 @@ get-bindings() {
 	echo '>>> i3 bindings!'
 	sed -n '/my bindings/,$p' ~/.config/i3/config \
 	| sed -nE 's/^.*(\$mod[^[:blank:]]+).+\$bind_suffix (.*)$/\1 » \2/p'
-}
-
-TOKEN() {
-	FROM="${1:?need to inform the abbreviation where!}"
-	read -sp 'Password: '
-	gpg \
-		--decrypt \
-		--quiet \
-		--batch \
-		--passphrase "$REPLY" \
-		"$PK_LOAD_CFGBKP/enkrypted/.nekot_$FROM.gpg" \
-	| xclip -selection clipboard -rmlastnl
-	unset REPLY; echo
 }
 
 mychecking() {
@@ -144,11 +131,31 @@ mychecking() {
 	\) \( -iname '*confli*' -o -name '*.swp' \)
 }
 
+TOKEN() {
+	FROM="${1:?need to inform the abbreviation where}"
+	read -sp 'Password: '
+	gpg \
+		--decrypt \
+		--quiet \
+		--batch \
+		--passphrase "$REPLY" \
+		"$PK_LOAD_CFGBKP/enkrypted/.nekot_$FROM.gpg" \
+		2>&- \
+	| sed -n '2p' \
+	| xclip -selection clipboard -rmlastnl
+	[[ ! "${PIPESTATUS[*]}" =~ [1-9]+ ]] && {
+		echo 'SUCCESS!'
+	} || {
+		echo 'FAILURE!'
+	}
+	unset REPLY
+}
+
 twcm() {
-	MODE=${1:?need a mode to set!}
-	FILE=${2:?need a file to create!}
+	MODE=${1:?need a mode to set}
+	FILE=${2:?need a file to create}
 	[ -e "$FILE" ] && {
-		echo "`basename "$0"`: file already exists!"
+		echo "`basename "$0"`: file already exists"
 		return 1
 	} || {
 		touch "$FILE" && chmod -v "$MODE" "$FILE"
@@ -168,7 +175,7 @@ hlct() {
 	elif [ $# -eq 2 ]; then
 		STMT="--syntax $1 '`realpath "$2"`'"
 	else
-		echo "$0: error: need one or two args!"
+		echo "$0: error: need one or two args"
 		exit 1
 	fi
 	cd /tmp/
@@ -228,7 +235,7 @@ PROMPT_COMMAND='history -a'
 TODO="$HOME/Documents/annotations/.todo-list.txt"
 
 rand() { RAND='0'; while [ "${#RAND}" -lt '4' ]; do RAND="$(("$RANDOM"%10000))"; done; }
-tlr() { sed -i "/${1:?need an id to remove!}/d" "$TODO"; clear; tla; }
+tlr() { sed -i "/${1:?need an id to remove}/d" "$TODO"; clear; tla; }
 tla() { rand; [ "$#" -eq '0' ] && cat "$TODO" || echo "(`hostname`) $RAND » $*" >> "$TODO"; }
 
 # =============================================================================================
